name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.jpeg
    - assets/momo.png
    - assets/pasta.png
    - assets/pizza.png
    - assets/image 4.png
    - assets/chilly potatoes.jpeg
    - assets/nachos.jpeg
    - assets/panner.jpeg
    - assets/wedges.jpeg